import { SignalLogEntry, TradeSignalData } from '../types';

const SIGNAL_LOG_KEY = 'dhaher_terminal_signal_log';

/**
 * Retrieves the signal log from localStorage.
 */
export const getSignalLog = (): SignalLogEntry[] => {
    try {
        const logJson = localStorage.getItem(SIGNAL_LOG_KEY);
        if (!logJson) return [];
        const log = JSON.parse(logJson) as SignalLogEntry[];
        // Sort by date, newest first
        return log.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    } catch (error) {
        console.error("Failed to parse signal log from localStorage", error);
        return [];
    }
};

/**
 * Adds a new signal to the log and saves it.
 * @param signal The new trade signal generated by the AI.
 * @returns The updated signal log.
 */
export const logSignal = (signal: TradeSignalData): SignalLogEntry => {
    const log = getSignalLog();
    
    const newLogEntry: SignalLogEntry = {
        id: new Date().toISOString() + Math.random(),
        pair: signal.pair,
        direction: signal.direction,
        entryType: signal.entryType,
        tradingStyle: signal.tradingStyle,
        setupModel: signal.setupModel,
        entry: parseFloat(signal.entry),
        stopLoss: parseFloat(signal.stopLoss),
        takeProfit: parseFloat(signal.takeProfit),
        rrr: signal.rrr,
        confidence: signal.confidence,
        timestamp: new Date().toISOString(),
        keyDrivers: signal.keyDrivers,
        riskAnalysis: signal.riskAnalysis,
        riskAmountUSD: parseFloat(signal.riskAmountUSD),
        positionSizeLots: parseFloat(signal.positionSizeLots),
        status: 'PENDING',
    };

    const updatedLog = [newLogEntry, ...log];
    
    try {
        localStorage.setItem(SIGNAL_LOG_KEY, JSON.stringify(updatedLog));
    } catch (error) {
        console.error("Failed to save signal log to localStorage", error);
    }

    return newLogEntry;
};

/**
 * Updates the status of an existing signal in the log.
 * @param signalId The ID of the signal to update.
 * @param status The new status.
 * @returns The updated signal log.
 */
export const updateSignalStatus = (signalId: string, status: SignalLogEntry['status']): SignalLogEntry[] => {
    const log = getSignalLog();
    const signalIndex = log.findIndex(s => s.id === signalId);

    if (signalIndex > -1) {
        log[signalIndex].status = status;
        try {
            localStorage.setItem(SIGNAL_LOG_KEY, JSON.stringify(log));
        } catch (error) {
            console.error("Failed to save updated signal log to localStorage", error);
        }
    }
    return log.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
};
